### ISSUE TITLE
save objects

### ISSUE THREAD

**Issue by MMYusuf** [etingof/pyasn1#98] opened 2017-10-25 09:43 UTC
Hi,
Is there a way to save asn1 schema objects? i tried pickle put it is not working for some reason. it does not allow` __reduce__` operation !
Thanks

**Comment by etingof** [comment] 2017-10-25 11:56
There were some fixes related to pickling in 0.3.7. Which pyasn1 version are you using?

If 0.3.7 still does not work, can you give me a short reproducer so I'd understand what you are trying to do?

Thanks!

**Comment by MMYusuf** [comment] 2017-10-25 12:19
I am using the latest version. Sure here is a sample : 

```
import pickle
from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful

class COORDINATEPAIR(univ.Sequence):
    pass
COORDINATEPAIR.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 0))
COORDINATEPAIR.componentType = namedtype.NamedTypes(
    namedtype.NamedType('xcoordinate', univ.Real().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('ycoordinate', univ.Real().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)

coor = COORDINATEPAIR()
coor['xcoordinate'] = 1
coor['ycoordinate'] = 1

outputf = open('CBE_data.pkl', 'wb')
pickler = pickle.Pickler(outputf, -1)
pickler.dump(coor)

with open('CBE_data.pkl', 'rb') as input:
    coor = pickle.load(input)

print(coor.prettyPrint())

```

**Comment by etingof** [comment] 2017-10-25 20:18
Just a quick thought while I'm looking into this issue - did you consider using ASN.1 codec for storing those objects in files? I understand that may not work if you have a mix of ASN.1 and other Python objects to deal with...

For posterity - this snippet works for me:

```
from pyasn1.type import univ, namedtype, tag
from pyasn1.codec.ber import encoder, decoder


class COORDINATEPAIR(univ.Sequence):
    tagSet = univ.Sequence.tagSet.tagImplicitly(
        tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 0)
    )
    componentType = namedtype.NamedTypes(
        namedtype.NamedType(
            'xcoordinate', univ.Real().subtype(
                implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)
            )
        ),
        namedtype.NamedType(
            'ycoordinate', univ.Real().subtype(
                implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)
            )
        )
    )

coor = COORDINATEPAIR()
coor['xcoordinate'] = 1
coor['ycoordinate'] = 1

with open('CBE_data.pkl', 'wb') as outputf:
     outputf.write(encoder.encode(coor))

with open('CBE_data.pkl', 'rb') as inputf:
    coor, _ = decoder.decode(inputf.read(), asn1Spec=COORDINATEPAIR())

print(coor.prettyPrint())
```

**Comment by etingof** [comment] 2017-10-25 20:40
Here is a [quick and easy fix](https://github.com/etingof/pyasn1/pull/99). You are welcome to test that branch while I'm adding some tests and reading some more on the Pickle thing.

Thanks!

**Comment by MMYusuf** [comment] 2017-10-26 05:42
>  I understand that may not work if you have a mix of ASN.1 and other Python objects to deal with...

Many thanks, the fix works fine now !

**Comment by etingof** [comment] 2017-10-29 15:04
Merged https://github.com/etingof/pyasn1/pull/99

**Closed by etingof** 2017-10-29 15:04 UTC
Labels: bug
