### ISSUE TITLE
UTF8 String bug

### ISSUE THREAD

**Issue by ph4r05** [etingof/pyasn1#65] opened 2017-08-27 19:33 UTC
Hello,

last few hours I've been debugging the problem after port to new API v0.3.3.

I am experiencing problem like this:
 - Python v2.7.13
 - Parsing 2.5.29.17 subjectAltName
 - `char.UTF8String()` is being parsed in a way `pyasn1.type.univ.OctetString` is passed in the constructor. 
 - `prettyIn()` of the `AbstractCharacterString` is called, which leads to call `unicode(value)` essentially leading to  `__unicode__()` call on the `OctetString`
- `OctetString` has default encoding `iso-8859-1`, as it stores `_value` as a `str` it tries to decode it in the default encoding `iso-8859-1`.
- This leads to malformed non-ASCII characters from the UTF8 string
- If I read the file manually the string is stored correctly as UTF8 string. 

I can provide the example if needed. 

Thanks a lot for suggestion.

**Comment by etingof** [comment] 2017-08-27 20:27
I think I understand the issue, but if you could provide a minimal reproducer, that would be helpful!

Thanks!

**Comment by ph4r05** [comment] 2017-08-27 21:17
Thanks for the prompt reply!
Here it is:

```
# -*- coding: utf-8 -*-

import unittest
import base64
from pyasn1.type import tag, namedtype, namedval, univ, char, useful
from pyasn1.codec.der.decoder import decode

test = '0C414D696E6973746572696F206465206C6120506F6CC3AD74696361205465727269746F7269616C2079' \
       '2041646D696E69737472616369C3B36E2050C3BA626C696361'
testb = base64.b16decode(test)
expected = u'Ministerio de la Política Territorial y Administración Pública'


class SimpleTest(unittest.TestCase):
    def test_utf8(self):
        utfbin = testb[2:]
        self.assertEqual(utfbin.decode('utf-8'), expected)

    def test_decode(self):
        asn1 = decode(testb, asn1Spec=char.UTF8String())
        res = asn1[0]

        print('Decoded type: %s, value: \n\t%s' % (type(res), str(res)))
        print('Decoded type: %s, value iso-8859-1 decoded: \n\t%s' % (type(res), str(res).decode('iso-8859-1')))

        self.assertEqual(unicode(res), expected)
        self.assertEqual(str(res).decode('utf-8'), expected)


if __name__ == '__main__':
    unittest.main()
```

**Comment by etingof** [comment] 2017-08-27 22:35
Alright, can you please try [this fix](https://github.com/etingof/pyasn1/tree/fixed-char-types-init) and let me know if it works for you?

The fix is basically to handle the case of `CharType(OctetStringType())` separately from other initializers because of the different unicode encodings they might have associated with.

**Comment by ph4r05** [comment] 2017-08-28 06:09
thanks for a quick fix! I will check it out properly soon. I quick tested it and the test is now passing, but another one fails - can be unrelated / bug in my code.

**Comment by etingof** [comment] 2017-08-29 14:05
Merged to master in the meanwhile.

**Closed** 2017-08-31 11:59 UTC
Labels: bug

**Comment by ph4r05** [comment] 2017-09-01 21:52
Thanks! The problem is fixed now.
